baseurl = "https://xn----7sbanriziekmikfpeh.online/"
languageCode = "bg"
title = "Разумна Сигурност Online"
theme = "kiss"
enableGitInfo = true

# Number of posts per page
Paginate = 5
enableRobotsTXT = true

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = ""                           # Adsense ID (ID only, without ca-pub-)
enableSocial = true                    # Adds OpenGraph and Twitter cards
homeTitle = "Разумна Сигурност Online" # Title for home page
poweredby = true                       # Adds powered by Hugo and Kiss below Copyright section

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

twitter = ""
github = ""
email = ""
linkedin = ""
facebook = ""
instagram = ""
codepen = ""

[blackfriday]
hrefTargetBlank = true
